---
apiVersion: v2
name: hcloud-cluster
type: application
version: 1.2.2
appVersion: 1.2.2
description: Kubernetes cluster for Hetzner Cloud
home: https://github.com/cloudhippie/hcloud-cluster
keywords: []
maintainers:
  - email: thomas@cloudhippie.de
    name: tboerger
    url: https://github.com/tboerger
sources:
  - https://github.com/cloudhippie/hcloud-cluster
dependencies:
  - name: prom-crds-proxy
    repository: oci://ghcr.io/cloudhippie/charts
    version: 1.0.0
  - condition: hcloud.ccm.enabled
    name: hcloud-ccm-proxy
    repository: oci://ghcr.io/cloudhippie/charts
    version: 1.1.0
  - condition: hcloud.csi.enabled
    name: hcloud-csi-proxy
    repository: oci://ghcr.io/cloudhippie/charts
    version: 1.0.1
  - condition: cluster.cni == 'calico'
    name: calico-cni-proxy
    repository: oci://ghcr.io/cloudhippie/charts
    version: 1.0.0
...
