apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "hcloud-cluster.clusterName" . }}-worker-unhealthy-5m
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-cluster.labels" . | nindent 4 }}
spec:
  clusterName: {{ include "hcloud-cluster.clusterName" . }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 10m
  remediationTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    name: worker-remediation-request
  selector:
    matchLabels:
      cluster: {{ include "hcloud-cluster.clusterName" . }}
  unhealthyConditions:
    - status: Unknown
      timeout: 180s
      type: Ready
    - status: "False"
      timeout: 180s
      type: Ready
